<?php

namespace Plugin\Zipcode\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\Zipcode\Entity\ZipCode;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends AbstractRepository
{
    /**
     * ConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, ZipCode::class);
    }

    /**
     * @param int $id
     *
     * @return null|ZipCode
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
